name: Full CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches :
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v4
             
      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install all dependencies
        run: npm ci --prefer-offline --network-timeout=100000   
        
      # - name: Run Tests
      #   run: npm test
        
      - name: Build
        run: |
          npm run build
          du -sh build/
        env:
          CI: false
          NODE_ENV: production
          GENERATE_SOURCEMAP: false
          INLINE_RUNTIME_CHUNK: false
          NODE_OPTIONS: --max_old_space_size=4096
        
    
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:etekanesh/front-teacher-panel.git
          BRANCH: build 
          FOLDER: build 
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }} 
          MESSAGE: "Build: ({sha}) {msg}" 
                
      # - name: Deploy to Server
      #   run: |
      #           echo "${{ secrets.SSH_PRIVATE_KEY }}" > deploy_key.pem
      #           chmod 600 deploy_key.pem
      #           cat deploy_key.pem
      #           ssh -v -o StrictHostKeyChecking=no -i deploy_key.pem root@62.60.211.99 "cd /srv/gpanel/nginx/build && git pull origin build"
